### ISSUE TITLE
No releases since recent patches?

### ISSUE THREAD

**Issue by nickeubank** [almost-matching-exactly/DAME-FLAME-Python-Package#46]
Hey DAME-FLAME team! 

I'm using this in class here at Duke, and just realized that a patch I put in last year for a reporting error (#34 ), while merged, is not in the pypi version because looks like the package hasn't had any releases since 2020. Any chance you could push a new release? Very confused students... :(

Thanks!

Nick

**Comment by nickeubank** [comment]
Is this just gonna end up a dead project? It's the best matching package for Python it seems, but if releases aren't gonna be coming out, maybe I should move my students to other libraries?

**Comment by nehargupta** [comment]
Hi Nick,
Sorry for the delayed response here! 

To answer your main question, no, we definitely don't plan for this to be a dead end project! I appreciate you using it with your class, and your feedback has all been insightful, super helpful changes that I'm excited to add. 

Delays are just due to my having a busy schedule with other things at this time and once I pass those, I'll be diving back into this. As far as a tentative timeline for changes, you'll either hear from me in about a month and a half, or from someone else on the team if they can get to it sooner. In the meantime, please do reach out if you have any other questions or want to talk to any of us about it.

**Comment by nickeubank** [comment]
OK, great. Happy to hire an RA to try and help / hire you if you're still Duke affiliated over the summer.

**Comment by nickeubank** [comment]
Hi All—any chance of this being updated? Gotta teach this on Tuesday... I would hate to have to go find a new package and give up on this library.

**Comment by nehargupta** [comment]
closing this -- lots of changes made recently and over the last year or so :) For future requests and questions, feel free to create a new issue or email us, etc.
